scoreboard players add @a kill 0
scoreboard players add @a propiedad 0
scoreboard players add @a prote 0
scoreboard players add @a _9999 0
scoreboard players add @a depa 0
scoreboard players add @a _Death 0
scoreboard players add @a trash 0
scoreboard players add @a clase 0
scoreboard players add @a time_10 0
scoreboard players add @a uiCooldown 0
