export const onJoinData = [
    "scoreboard objectives add clase dummy §dClass",
    "scoreboard players add @s clase 0",
    "scoreboard objectives add uiCooldown dummy §dUI-Cooldown",
    "scoreboard players add @s uiCooldown 0",
    "scoreboard objectives add resistance dummy",
    "scoreboard players add @s resistance 0",
    "scoreboard objectives add absorsion dummy",
    "scoreboard players add @s absorsion 0",
    "scoreboard objectives add speed dummy",
    "scoreboard players add @s speed 0",
    "scoreboard objectives add propiedad dummy",
    "scoreboard players add @s propiedad 0",
    "scoreboard objectives add depa dummy §l§o§bDepartment",
    "scoreboard players add @a depa 0",
    "scoreboard objectives add _Death dummy §l§o§cMuertes",
    "scoreboard players add @a _Death 0",
    "",
    "scoreboard objectives add time_00 dummy §l§o§eSeconds",
    "scoreboard objectives add time_01 dummy §l§o§eMinutes",
    "scoreboard objectives add time_11 dummy §l§o§eHours",
    "scoreboard objectives add time_10 dummy §l§o§eDays",
    "scoreboard players add @a time_10 0",
    "scoreboard objectives add server dummy §dUntravel§eMx",
    "gamerule sendcommandfeedback false",
    "gamerule commandblockoutput false",
    "scoreboard objectives add _9999 dummy Banco",
    "scoreboard objectives add _0000 dummy §bSaldo",
    "scoreboard objectives add prote dummy",
    "scoreboard players add @a prote 0",
    "scoreboard objectives add trash dummy §eTrashPeople",
    "scoreboard players add @a trash 0",
    "scoreboard objectives add rank_status dummy §l§o§eRangos",
    "scoreboard objectives add kill dummy §l§o§cKills",
    "scoreboard players add @a kill 0",
    "scoreboard objectives add omega dummy §l§o§cTecutli-Omega",
    "",
    "scoreboard objectives add cooldown_p_1 dummy",
    "scoreboard objectives add cooldown_p_2 dummy",
    "scoreboard objectives add cooldown_p_3 dummy",
    "scoreboard objectives add cooldown_w_1 dummy",
    "scoreboard objectives add cooldown_w_2 dummy",
    "scoreboard objectives add cooldown_w_3 dummy",
    "scoreboard objectives add cooldown_m_1 dummy",
    "scoreboard objectives add cooldown_m_2 dummy",
    "scoreboard objectives add cooldown_m_3 dummy",
    "scoreboard objectives add cooldown_n_1 dummy",
    "scoreboard objectives add cooldown_n_2 dummy",
    "scoreboard objectives add cooldown_n_3 dummy",
    "scoreboard objectives add cooldown_a_1 dummy",
    "scoreboard objectives add cooldown_a_2 dummy",
    "scoreboard objectives add cooldown_a_3 dummy",
    "scoreboard objectives add off dummy §l§o§binactivo",
    "scoreboard objectives add on dummy §l§o§bactivo",
    "scoreboard objectives add wither_Arena dummy",
    "scoreboard objectives add Mana dummy"

];